/** addrmodes.c
*/
#include <testfwk.h>
#include <stdlib.h>
#include <mcs51reg.h>
#include <stdint.h>


typedef struct _PORT3_Bits
{
    unsigned char  PIN0:1;
    unsigned char  PIN1:1;
    unsigned char  PIN2:1;
    unsigned char  PIN3:1;
    unsigned char  PIN4_7:4;
} PORT3_Bits;

typedef union
{
    unsigned char U;                  /**< \brief Unsigned access */
    char I;                  /**< \brief Signed access */
    PORT3_Bits B;           /**< \brief Bitfield access */
} TPORT3;

#define PORT3 (*(__sfrdata volatile  TPORT3*)0xB0u)
__sfrdata __at(0xB0) TPORT3 PORT3T;

void
test(void)
{
//#warning "Warning Generated by #warning"
//  P3=0xAA;
//  while(P3 == 0xAA);
//  PORT3.U=0x9E;
//  while( P3 == 0x9E );
//  while( PORT3.U == 0x9E );
//  while( PORT3.B.PIN0 == 0);
//  while( PORT3.B.PIN1 == 1);
//  while( PORT3.B.PIN2 == 1);
//  while( PORT3.B.PIN3 == 1);
//  while( PORT3.B.PIN4_7 == 0x9);
//  PORT3.B.PIN4_7=PORT3.B.PIN1+PORT3.B.PIN2;
//  while( PORT3.B.PIN4_7 == 2);
//  PORT3.U=PORT3.B.PIN4_7;
//  while( PORT3.U == 2);
//  while( PORT3.B.PIN4_7 == 0);
}

void
testAbs(void)
{
#warning "Warning Generated by #warning"
  unsigned char i;
  P3=0xAA;
  ASSERT( P3 == 0xAA );
  PORT3.U=0x9E;
  ASSERT( P3 == 0x9E );
  ASSERT( PORT3.U == 0x9E );
  ASSERT( PORT3.B.PIN0 == 0);
  ASSERT( PORT3.B.PIN1 == 1);
  ASSERT( PORT3.B.PIN2 == 1);
  ASSERT( PORT3.B.PIN3 == 1);
  ASSERT( PORT3.B.PIN4_7 == 0x9);
  PORT3.B.PIN4_7=PORT3.B.PIN1+PORT3.B.PIN2;
  ASSERT( PORT3.B.PIN4_7 == 2);
  ASSERT( PORT3.U == 0x2e);
  i=PORT3.B.PIN4_7;
  ASSERT( i == 2);
  i=PORT3.B.PIN1;
  ASSERT( i == 1);
  PORT3.U=PORT3.B.PIN4_7;
  ASSERT( PORT3.U == 0x2);

  P3=0xAA;
  ASSERT( P3 == 0xAA );
  PORT3T.U=0x9E;
  ASSERT( P3 == 0x9E );
  ASSERT( PORT3T.U == 0x9E );
  ASSERT( PORT3T.B.PIN0 == 0);
  ASSERT( PORT3T.B.PIN1 == 1);
  ASSERT( PORT3T.B.PIN2 == 1);
  ASSERT( PORT3T.B.PIN3 == 1);
  ASSERT( PORT3T.B.PIN4_7 == 0x9);
  PORT3T.B.PIN4_7=PORT3T.B.PIN1+PORT3T.B.PIN2;
  ASSERT( PORT3T.B.PIN4_7 == 2);
  ASSERT( PORT3T.U == 0x2e);
  i=PORT3T.B.PIN4_7;
  ASSERT( i == 2);
  i=PORT3T.B.PIN1;
  ASSERT( i == 1);
  PORT3T.U=PORT3T.B.PIN4_7;
  ASSERT( PORT3T.U == 0x2);

}

