/** addrmodes.c
*/
#include <testfwk.h>
#include <stdlib.h>
#include <mcs51reg.h>
#include <stdint.h>

__data unsigned char temp;

void
testwrite(void)
{
  (* (__data unsigned char *)(0x7F))=0xBB;
}

void
testread(void)
{
  temp=(* (__data unsigned char *)(0x7F));
}

__data unsigned long a;
__data unsigned long b;
__data unsigned long *pa;
__data unsigned long *pb;

void
testp(void)
{
  __data unsigned long *pa;
  __data unsigned long *pb;
  pa=&a;
  pb=&b;
  *pa=*pb;
}

void
test(void)
{
  (* (__data unsigned char *)(0x7F))=0xBB;
}

void
testAbs(void)
{
#warning "Warning Generated by #warning"
  P3=0xAA;
  ASSERT( P3 == 0xAA );
  (* (__sfrdata unsigned char *)(0xB0))=0xBB;
  ASSERT( P3 == 0xBB );
  P3=0xCC;
  temp=(* (__sfrdata unsigned char *)(0xB0));
  ASSERT( temp == 0xCC );
}

